In [1]:
# importamos las librerías que necesitamos

# Tratamiento de datos
# -----------------------------------------------------------------------
import pandas as pd
import numpy as np

# Imputación de nulos usando métodos avanzados estadísticos
# -----------------------------------------------------------------------
from sklearn.impute import SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer

# Librerías de visualización
# -----------------------------------------------------------------------
import seaborn as sns
import matplotlib.pyplot as plt
# Configuración
# -----------------------------------------------------------------------
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

#-------------------------------------
from datetime import datetime

In [2]:
#Utilizamos pandas para leer el .csv, indicando ccolumna 0 como índice de nuestro df

df = pd.read_csv('../archivos/hr_raw_data_final.csv', index_col=[0])

## 1. DESCOMPONEMOS EL DF ##

Vemos la estructura del dataframe y qué contiene

In [3]:
#Vistazo rápido al dataframe, inicio, final y fila random

df.head()

age attrition businesstravel    dailyrate                department  \
0  51        No            NaN  2015.722222                       NaN   
1  52        No            NaN  2063.388889                       NaN   
2  42        No  travel_rarely  1984.253968   Research & Development    
3  47        No  travel_rarely  1771.404762                       NaN   
4  46        No            NaN  1582.771346                       NaN   

   distancefromhome  education    educationfield  employeecount  \
0                 6          3               NaN              1   
1                 1          4     Life Sciences              1   
2                 4          2  Technical Degree              1   
3                 2          4           Medical              1   
4                 3          3  Technical Degree              1   

   employeenumber  environmentsatisfaction  gender  hourlyrate  \
0               1                        1       0         NaN   
1               2                        3       0         NaN   
2               3                        3       0         NaN   
3               4                        1       1         NaN   
4               5                        1       1         NaN   

   jobinvolvement  joblevel              jobrole  jobsatisfaction  \
0               3         5   resEArch DIREcToR                 3   
1               2         5             ManAGeR                 3   
2               3         5             ManaGER                 4   
3               3         4   ReseArCH DIrECtOr                 3   
4               4         4     sAleS EXECUtIve                 1   

  maritalstatus monthlyincome monthlyrate  numcompaniesworked over18 overtime  \
0           NaN     16280,83$   42330,17$                   7      Y       No   
1           NaN           NaN   43331,17$                   0    NaN      NaN   
2       Married           NaN   41669,33$                   1    NaN       No   
3       Married     14307,50$   37199,50$                   3      Y      NaN   
4      Divorced     12783,92$   33238,20$                   2      Y       No   

   percentsalaryhike performancerating  relationshipsatisfaction  \
0                 13               3,0                         3   
1                 14               3,0                         1   
2                 11               3,0                         4   
3                 19               3,0                         2   
4                 12               3,0                         4   

  standardhours  stockoptionlevel totalworkingyears  trainingtimeslastyear  \
0     Full Time                 0               NaN                      5   
1           NaN                 1              34,0                      5   
2           NaN                 0              22,0                      3   
3     Full Time                 2               NaN                      2   
4           NaN                 1               NaN                      5   

  worklifebalance  yearsatcompany yearsincurrentrole  yearssincelastpromotion  \
0             3,0              20                NaN                       15   
1             3,0              33                NaN                       11   
2             NaN              22                NaN                       11   
3             NaN              20                NaN                        5   
4             3,0              19                NaN                        2   

   yearswithcurrmanager sameasmonthlyincome  datebirth      salary  \
0                    15           16280,83$       1972  195370,00$   
1                     9                 NaN       1971  199990,00$   
2                    15                 NaN       1981  192320,00$   
3                     6           14307,50$       1976  171690,00$   
4                     8           12783,92$       1977         NaN   

                        roledepartament  numberchildren remotework  
0     

In [4]:
df.tail()

age attrition businesstravel    dailyrate department  distancefromhome  \
1673  43        No            NaN   488.944444        NaN               -26   
1674  47        No            NaN  1973.984127        NaN                26   
1675  29        No  travel_rarely   290.035510        NaN                15   
1676  47        No  travel_rarely  1032.487286        NaN                 4   
1677  32        No            NaN   556.256661        NaN                 2   

      education educationfield  employeecount  employeenumber  \
1673          3        Medical              1             824   
1674          4            NaN              1            1087   
1675          3            NaN              1             528   
1676          3  Life Sciences              1              76   
1677          2  Life Sciences              1             401   

      environmentsatisfaction  gender  hourlyrate  jobinvolvement  joblevel  \
1673                        2       1         NaN               4         1   
1674                        4       1         NaN               3         5   
1675                        3       0         NaN               3         1   
1676                        3       1         NaN               2         3   
1677                        4       1   69.532083               3         2   

                       jobrole  jobsatisfaction maritalstatus monthlyincome  \
1673       rESEaRcH SciEnTiST                 3        Single      3949,17$   
1674                  mANager                 3       Married     15943,72$   
1675       reSearch sCienTiSt                 4           NaN           NaN   
1676   maNufACTURING DIREctOr                 2      Divorced      8339,32$   
1677       resEArch scIENTisT                 3        Single           NaN   

     monthlyrate  numcompaniesworked over18 overtime  percentsalaryhike  \
1673   10267,83$                   4    NaN      NaN                 12   
1674   41453,67$                   3      Y       No                 11   
1675    6090,75$                   1    NaN       No                 19   
1676   21682,23$                   8    NaN      Yes                 12   
1677   11681,39$                   4      Y      Yes                 14   

     performancerating  relationshipsatisfaction standardhours  \
1673               3,0                         4           NaN   
1674               3,0                         3     Full Time   
1675               3,0                         1     Part Time   
1676               NaN                         3     Part Time   
1677               3,0                         4     Part Time   

      stockoptionlevel totalworkingyears  trainingtimeslastyear  \
1673                 0               NaN                      2   
1674                 1              27,0                      2   
1675                 0               6,0                      1   
1676                 1               NaN                      4   
1677                 0              10,0                      2   

     worklifebalance  yearsatcompany yearsincurrentrole  \
1673             3,0               3                NaN   
1674             3,0               5                NaN   
1675             3,0               6                NaN   
1676             3,0              22                NaN   
1677             3,0               8                NaN   

      yearssincelastpromotion  yearswithcurrmanager sameasmonthlyincome  \
1673                        1                     2            3949,17$   
1674                        1                     0           15943,72$   
1675                        1                     5                 NaN   
1676                       14                    10            8339,32$   
1677                        0                     7                 NaN   

      datebirth      salary roledepartament  numberchildren remotework  
1673       1980         NaN             NaN             NaN

In [5]:
df.sample()

age attrition businesstravel   dailyrate department  distancefromhome  \
548  28        No  travel_rarely  329.746032        NaN                19   

     education educationfield  employeecount  employeenumber  \
548          4        Medical              1             549   

     environmentsatisfaction  gender  hourlyrate  jobinvolvement  joblevel  \
548                        4       0         NaN               2         1   

                     jobrole  jobsatisfaction maritalstatus monthlyincome  \
548   LAbOrATOry techNicIan                 1       Married      2663,33$   

    monthlyrate  numcompaniesworked over18 overtime  percentsalaryhike  \
548    6924,67$                   1      Y      NaN                 12   

    performancerating  relationshipsatisfaction standardhours  \
548               3,0                         3           NaN   

     stockoptionlevel totalworkingyears  trainingtimeslastyear  \
548                 3               6,0                      2   

    worklifebalance  yearsatcompany yearsincurrentrole  \
548             3,0               6                NaN   

     yearssincelastpromotion  yearswithcurrmanager sameasmonthlyincome  \
548                        3                     3            2663,33$   

     datebirth     salary roledepartament  numberchildren remotework  
548       1995  31960,00$             NaN             NaN          0

In [6]:
#Printeamos la forma del df

print(f'Num. filas: {df.shape[0]}')
print(f'Num. columnas: {df.shape[1]}')

Num. filas: 1678
Num. columnas: 41


In [ ]:
#Vemos el nombre de todas las columnas

df.columns

# DATOS ESTADÍSTICOS DEL DF #

In [ ]:
#Vemos datos como el conteo, media, mediana, min, max, etc... de las COLUMNAS NUMÉRICAS

df.describe().T

In [ ]:
#De la COLUMNAS CATEGÓRICAS (es decir, no numéricas) observamos el conteo, el número de valores únicos, top y frecuencia

df.describe(include = "object").T

In [ ]:
#Sacamos los valores únicos de cada columna

for columna in df:
    print(f'La columna {columna} tiene los siguientes valores únicos:')
    print(df[columna].unique())
    print('----------------------------\n----------------------------------')

# % de nulos de todas las columnas

In [ ]:
nulos = df.isnull().sum()
nulos

In [ ]:
# Aplicamos 2 decimales con round
(nulos/df.shape[0]*100).round(2)

In [13]:
#Verificamos que las filas duplicadas, sólo están duplicadas una vez

df.duplicated().sum()

64

In [14]:
df.duplicated(keep=False).sum()

128

## COMENZAMOS EL EDA

In [15]:
df[df.duplicated(keep=False)].sort_values('employeenumber')

#Hemos comprobado que las filas duplicadas son empleados duplicados, por tanto, se pueden eliminar

age attrition businesstravel    dailyrate department  distancefromhome  \
8     41        No            NaN  1712.182540        NaN                 2   
1656  41        No            NaN  1712.182540        NaN                 2   
60    36        No            NaN   610.174603        NaN                 5   
1652  36        No            NaN   610.174603        NaN                 5   
1676  47        No  travel_rarely  1032.487286        NaN                 4   
...   ..       ...            ...          ...        ...               ...   
1638  48        No  travel_rarely   417.960317        NaN                 2   
1657  45        No  travel_rarely   495.753968        NaN                 2   
1568  45        No  travel_rarely   495.753968        NaN                 2   
1671  31        No            NaN   556.256661        NaN                12   
1607  31        No            NaN   556.256661        NaN                12   

      education educationfield  employeecount  employeenumber  \
8             5            NaN              1               9   
1656          5            NaN              1               9   
60            2            NaN              1              61   
1652          2            NaN              1              61   
1676          3  Life Sciences              1              76   
...         ...            ...            ...             ...   
1638          5            NaN              1            1568   
1657          3          Other              1            1569   
1568          3          Other              1            1569   
1671          3        Medical              1            1608   
1607          3        Medical              1            1608   

      environmentsatisfaction  gender  hourlyrate  jobinvolvement  joblevel  \
8                           2       1         NaN               3         4   
1656                        2       1         NaN               3         4   
60                          4       0         NaN               3         2   
1652                        4       0         NaN               3         2   
1676                        3       1         NaN               2         3   
...                       ...     ...         ...             ...       ...   
1638                        2       1         NaN               3         2   
1657                        4       0         NaN               3         2   
1568                        4       0         NaN               3         2   
1671                        4       1         NaN               3         2   
1607                        4       1         NaN               3         2   

                          jobrole  jobsatisfaction maritalstatus  \
8                        mANAGEr                 1       Married   
1656                     mANAGEr                 1       Married   
60         lAboratORy TeChNiCiaN                 2        Single   
1652       lAboratORy TeChNiCiaN                 2        Single   
1676      maNufACTURING DIREctOr                 2      Divorced   
...                           ...              ...           ...   
1638             sALES EXEcuTIVe                 4       Married   
1657             sAles executiVe                 2           NaN   
1568             sAles executiVe                 2           NaN   
1671   HEaltHCarE REPreSENtAtIve                 4           NaN   
1607   HEaltHCarE REPreSENtAtIve                 4           NaN   

     monthlyincome monthlyrate  numcompaniesworked over18 overtime  \
8        13829,17$   35955,83$                   7    NaN       No   
1656     13829,17$   35955,83$                   7    NaN       No   
60        4928,33$   12813,67$                   8      Y       No   
1652      4928,33$   12813,67$                   8      Y       No   
1676      8339,32$   21682,23$                   8    NaN      Yes   
...            ...         ...                 ...    ...      ...   
1638      3375,83$ 

In [16]:
df.drop_duplicates(inplace=True)

In [17]:
#Vemos qué valores únicos tiene la columna 'employeecount'

df['employeecount'].unique()

array([1], dtype=int64)

In [18]:
#Como sólo tiene un valor único y no aporta a nuestro df, podemos eliminar la columna

df.drop(['employeecount'], axis=1, inplace=True)

In [19]:
#Comprobamos que las columnas 'monthlyincome' y 'sameasmonthlyincome' son iguales, y si lo son, borramos una de ellas

lista1 = list(df['monthlyincome'])
lista2 = list(df['sameasmonthlyincome'])
if lista1 == lista2:
    print('Son iguales')

print(lista1)
print('---------------------------------')
print(lista2)

Son iguales
['16280,83$', nan, nan, '14307,50$', '12783,92$', '14311,67$', '8339,32$', nan, '13829,17$', '15943,72$', '16644,17$', nan, nan, nan, '15943,72$', '15034,17$', '16038,33$', '12783,92$', '4492,84$', '8339,32$', '8956,67$', nan, nan, nan, '5167,50$', nan, nan, '4492,84$', '4492,84$', '3334,17$', '8705,83$', '8339,32$', '15943,72$', '4492,84$', '4492,84$', '8339,32$', nan, '2675,00$', '8555,00$', '8729,17$', nan, '3934,17$', '12783,92$', nan, '3845,83$', '4492,84$', '8339,32$', '14132,50$', nan, nan, '8339,32$', '12783,92$', '8588,33$', '15943,72$', '4492,84$', '4505,00$', nan, nan, '4918,33$', nan, '4928,33$', nan, '5538,33$', '4492,84$', nan, nan, '11100,00$', nan, nan, '5572,50$', '4492,84$', nan, '12783,92$', nan, nan, '8339,32$', '4492,84$', '8339,32$', nan, '11560,00$', '8339,32$', '8339,32$', '8339,32$', '8339,32$', '15870,83$', '13345,83$', '8010,83$', nan, '12783,92$', '3588,33$', '14205,00$', '8339,32$', '4222,50$', '8339,32$', nan, '4492,84$', nan, '3076,67$', '1594

In [20]:
df.drop('sameasmonthlyincome', axis=1, inplace=True)

In [21]:
#Vamos a sustituir en la columna 'genre' los 0 por 'M' y los 1 por 'F'
df['gender']

0       0
1       0
2       0
3       1
4       1
       ..
1609    0
1610    0
1611    0
1612    0
1613    0
Name: gender, Length: 1614, dtype: int64

In [22]:
df['gender'] = df['gender'].replace(1, 'F').replace(0, 'M')

In [23]:
df['gender'].describe() 

count     1614
unique       2
top          M
freq       971
Name: gender, dtype: object

In [24]:
#Aplicamos lower() a la columna 'roledeparment'

df['roledepartament'] = df['roledepartament'].str.lower()  #Usamos .str para aplicar a cada string de la columna

In [25]:
df['roledepartament'].unique()

array([nan, ' manager  -  research & development ',
       ' healthcare representative  -  research & development ',
       ' sales executive  -  sales ',
       ' laboratory technician  -  research & development ',
       ' manufacturing director  -  research & development ',
       ' research scientist  -  research & development ',
       ' research director  -  research & development ',
       ' human resources  -  human resources ', ' manager  -  sales ',
       ' sales representative  -  sales ',
       ' manager  -  human resources '], dtype=object)

In [27]:
#Repetimos el proceso para la columna 'jobrole'

df['jobrole']= df['jobrole'].str.lower().str.strip()

In [28]:
df['jobrole'].unique()

array(['research director', 'manager', 'sales executive',
       'manufacturing director', 'research scientist',
       'healthcare representative', 'laboratory technician',
       'sales representative', 'human resources'], dtype=object)

In [343]:
#Borramos la columna 'numberchildren' 
df.drop('numberchildren', axis=1, inplace=True)

In [344]:
df.drop('over18', axis=1, inplace=True)

In [345]:
df.loc[:,['roledepartament', 'jobrole', 'department']].sample(5)

roledepartament  \
299                                                 NaN   
506                                                 NaN   
726    laboratory technician  -  research & developm...   
1208                                                NaN   
143                                                 NaN   

                       jobrole                department  
299                   manager                        NaN  
506                   manager                        NaN  
726     laboratory technician    Research & Development   
1208   manufacturing director                        NaN  
143         research director                        NaN

In [346]:
df['roledepartament'].unique()

array([nan, ' manager  -  research & development ',
       ' healthcare representative  -  research & development ',
       ' sales executive  -  sales ',
       ' laboratory technician  -  research & development ',
       ' manufacturing director  -  research & development ',
       ' research scientist  -  research & development ',
       ' research director  -  research & development ',
       ' human resources  -  human resources ', ' manager  -  sales ',
       ' sales representative  -  sales ',
       ' manager  -  human resources '], dtype=object)

In [347]:
df['jobrole'].unique()

array([' research director ', ' manager ', ' sales executive ',
       ' manufacturing director ', ' research scientist ',
       ' healthcare representative ', ' laboratory technician ',
       ' sales representative ', ' human resources '], dtype=object)

In [348]:
df['department'].unique()

array([nan, ' Research & Development ', ' Sales ', ' Human Resources '],
      dtype=object)

In [349]:
#Conclusión (a la que llega María): NO todos los managers tienen department, 
# pero se podría obtener si fuese necesario con ayuda de eduationfield (a lo mejor)

#df.loc[:, df['jobrole'] == ' manager '] -> No funciona pq le estamos pidiendo TODAS las filas, y no todas cumplen la condición  == ' manager '

df.loc[df['jobrole'] == ' manager '].sample(5)  #Si le quitamos los espacios a 'manager' no funciona, por lo mencionado anteriormente

age attrition     businesstravel    dailyrate                department  \
1241  55        No      travel_rarely  1582.771346                       NaN   
53    43        No                NaN  1973.984127                       NaN   
491   33        No  travel_frequently  1225.507937   Research & Development    
26    52       Yes                NaN  2047.500000                       NaN   
166   58        No         non-travel  1582.771346                       NaN   

      distancefromhome  education educationfield  employeenumber  \
1241                 8          3            NaN            1242   
53                   6          3        Medical              54   
491                  5          4            NaN             492   
26                   2          1            NaN              27   
166                  2          3        Medical             167   

      environmentsatisfaction gender  hourlyrate  jobinvolvement  joblevel  \
1241                        4      F  197.846418               3         4   
53                          1      F         NaN               2         5   
491                         4      F         NaN               3         3   
26                          1      F         NaN               1         5   
166                         2      M  197.846418               3         4   

        jobrole  jobsatisfaction maritalstatus monthlyincome monthlyrate  \
1241   manager                 3      Divorced     12783,92$   33238,20$   
53     manager                 3       Married     15943,72$   41453,67$   
491    manager                 2       Married      9898,33$   25735,67$   
26     manager                 4       Married           NaN   42997,50$   
166    manager                 2      Divorced     12783,92$   33238,20$   

      numcompaniesworked overtime  percentsalaryhike performancerating  \
1241                   2      Yes                 14               3,0   
53                     7       No                 13               3,0   
491                    6      NaN                 11               NaN   
26                     1       No                 15               3,0   
166                    4       No                 22               4,0   

      relationshipsatisfaction standardhours  stockoptionlevel  \
1241                         3     Full Time                 3   
53                           4           NaN                 0   
491                          2           NaN                 2   
26                           4     Full Time                 1   
166                          4     Full Time                 1   

     totalworkingyears  trainingtimeslastyear worklifebalance  yearsatcompany  \
1241              21,0                      2             3,0               5   
53                21,0                      2             3,0              16   
491               12,0                      2             3,0              10   
26                33,0                      3             3,0              32   
166               37,0                      0             2,0              16   

     yearsincurrentrole  yearssincelastpromotion  yearswithcurrmanager  \
1241                NaN                        0                     2   
53                  NaN                        6                    14   
491                 NaN                        8                     8   
26                  NaN                        6                     9   
166                 NaN                       14                    14   

      datebirth      salary                       roledepartament remotework  
1241       1968  153407,07$                                   NaN        Yes  
53         1980         NaN                                   NaN        Yes  
491        1990         NaN   manager  -  research & development        True  
26         1971  198450,00$                                   NaN          1  
166        1965  153

In [350]:
# columnas a las que aplicar el strip_> roledepartament, jobrole, department
df['department'] = df['department'].str.strip() 


In [351]:
df['roledepartament'] = df['roledepartament'].str.strip() 
df['jobrole'] = df['jobrole'].str.strip() 

In [352]:
# Comprobamos que se ha aplicado correctamente el strip
print(df['department'].unique())
print(df['jobrole'].unique())
print(df['roledepartament'].unique())

[nan 'Research & Development' 'Sales' 'Human Resources']
['research director' 'manager' 'sales executive' 'manufacturing director'
 'research scientist' 'healthcare representative' 'laboratory technician'
 'sales representative' 'human resources']
[nan 'manager  -  research & development'
 'healthcare representative  -  research & development'
 'sales executive  -  sales'
 'laboratory technician  -  research & development'
 'manufacturing director  -  research & development'
 'research scientist  -  research & development'
 'research director  -  research & development'
 'human resources  -  human resources' 'manager  -  sales'
 'sales representative  -  sales' 'manager  -  human resources']


In [353]:
# Nos aseguramos que todas las palabras en minus
df['department'] = df['department'].str.lower() 
df['jobrole'] = df['jobrole'].str.lower() 
df['roledepartament'] = df['roledepartament'].str.lower() 

In [354]:
# Comprobamos que se ha aplicado correctamente el lower
print(df['department'].unique())
print(df['jobrole'].unique())
print(df['roledepartament'].unique())

[nan 'research & development' 'sales' 'human resources']
['research director' 'manager' 'sales executive' 'manufacturing director'
 'research scientist' 'healthcare representative' 'laboratory technician'
 'sales representative' 'human resources']
[nan 'manager  -  research & development'
 'healthcare representative  -  research & development'
 'sales executive  -  sales'
 'laboratory technician  -  research & development'
 'manufacturing director  -  research & development'
 'research scientist  -  research & development'
 'research director  -  research & development'
 'human resources  -  human resources' 'manager  -  sales'
 'sales representative  -  sales' 'manager  -  human resources']


In [355]:
df.head()

age attrition businesstravel    dailyrate              department  \
0  51        No            NaN  2015.722222                     NaN   
1  52        No            NaN  2063.388889                     NaN   
2  42        No  travel_rarely  1984.253968  research & development   
3  47        No  travel_rarely  1771.404762                     NaN   
4  46        No            NaN  1582.771346                     NaN   

   distancefromhome  education    educationfield  employeenumber  \
0                 6          3               NaN               1   
1                 1          4     Life Sciences               2   
2                 4          2  Technical Degree               3   
3                 2          4           Medical               4   
4                 3          3  Technical Degree               5   

   environmentsatisfaction gender  hourlyrate  jobinvolvement  joblevel  \
0                        1      M         NaN               3         5   
1                        3      M         NaN               2         5   
2                        3      M         NaN               3         5   
3                        1      F         NaN               3         4   
4                        1      F         NaN               4         4   

             jobrole  jobsatisfaction maritalstatus monthlyincome monthlyrate  \
0  research director                3           NaN     16280,83$   42330,17$   
1            manager                3           NaN           NaN   43331,17$   
2            manager                4       Married           NaN   41669,33$   
3  research director                3       Married     14307,50$   37199,50$   
4    sales executive                1      Divorced     12783,92$   33238,20$   

   numcompaniesworked overtime  percentsalaryhike performancerating  \
0                   7       No                 13               3,0   
1                   0      NaN                 14               3,0   
2                   1       No                 11               3,0   
3                   3      NaN                 19               3,0   
4                   2       No                 12               3,0   

   relationshipsatisfaction standardhours  stockoptionlevel totalworkingyears  \
0                         3     Full Time                 0               NaN   
1                         1           NaN                 1              34,0   
2                         4           NaN                 0              22,0   
3                         2     Full Time                 2               NaN   
4                         4           NaN                 1               NaN   

   trainingtimeslastyear worklifebalance  yearsatcompany yearsincurrentrole  \
0                      5             3,0              20                NaN   
1                      5             3,0              33                NaN   
2                      3             NaN              22                NaN   
3                      2             NaN              20                NaN   
4                      5             3,0              19                NaN   

   yearssincelastpromotion  yearswithcurrmanager  datebirth      salary  \
0                       15                    15       1972  195370,00$   
1                       11                     9       1971  199990,00$   
2                       11                    15       1981  192320,00$   
3                        5                     6       1976  171690,00$   
4                        2                     8       1977         NaN   

                      roledepartament remotework  
0                                 NaN        Yes  
1                                 NaN          1  
2  manager  -  research & development          1  
3                                 NaN      False  
4                                 NaN          0

In [356]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1614 entries, 0 to 1613
Data columns (total 37 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   age                       1614 non-null   object 
 1   attrition                 1614 non-null   object 
 2   businesstravel            842 non-null    object 
 3   dailyrate                 1614 non-null   float64
 4   department                302 non-null    object 
 5   distancefromhome          1614 non-null   int64  
 6   education                 1614 non-null   int64  
 7   educationfield            869 non-null    object 
 8   employeenumber            1614 non-null   int64  
 9   environmentsatisfaction   1614 non-null   int64  
 10  gender                    1614 non-null   object 
 11  hourlyrate                404 non-null    float64
 12  jobinvolvement            1614 non-null   int64  
 13  joblevel                  1614 non-null   int64  
 14  jobrole      

In [357]:
def cambiar_tipo_dato(col):
    try: 
        if pd.isna(col):  # Verificar si el valor es NaN
            return np.nan
        col = col.replace(",", ".")  # Reemplazar la coma por punto
        return int(float(col))  # Convertir primero a float, luego a int
    except:
        return np.nan

# GRUPO 1

In [358]:
# TAREA 4 COLUMNA AGE

from datetime import datetime # Si funciona -> PDT: Anadir libreria al inicio del jupyter
# Inicialmente la columna age tiene algunos anios escritos como texto y es de tipo object
# Se comprueba que no hay valores nulos en datebirth y que son int de 4 digitos
# Age tenia datos actualizados hasta el 2023
def actualizar_edad(datebirth):
    año_actual = datetime.now().year
    edad = año_actual - int(datebirth) # datebirth tiene solo el año de nacimiento
    return edad

df['age'] = df['datebirth'].apply(actualizar_edad)

In [359]:
df.head()

age attrition businesstravel    dailyrate              department  \
0   52        No            NaN  2015.722222                     NaN   
1   53        No            NaN  2063.388889                     NaN   
2   43        No  travel_rarely  1984.253968  research & development   
3   48        No  travel_rarely  1771.404762                     NaN   
4   47        No            NaN  1582.771346                     NaN   

   distancefromhome  education    educationfield  employeenumber  \
0                 6          3               NaN               1   
1                 1          4     Life Sciences               2   
2                 4          2  Technical Degree               3   
3                 2          4           Medical               4   
4                 3          3  Technical Degree               5   

   environmentsatisfaction gender  hourlyrate  jobinvolvement  joblevel  \
0                        1      M         NaN               3         5   
1                        3      M         NaN               2         5   
2                        3      M         NaN               3         5   
3                        1      F         NaN               3         4   
4                        1      F         NaN               4         4   

             jobrole  jobsatisfaction maritalstatus monthlyincome monthlyrate  \
0  research director                3           NaN     16280,83$   42330,17$   
1            manager                3           NaN           NaN   43331,17$   
2            manager                4       Married           NaN   41669,33$   
3  research director                3       Married     14307,50$   37199,50$   
4    sales executive                1      Divorced     12783,92$   33238,20$   

   numcompaniesworked overtime  percentsalaryhike performancerating  \
0                   7       No                 13               3,0   
1                   0      NaN                 14               3,0   
2                   1       No                 11               3,0   
3                   3      NaN                 19               3,0   
4                   2       No                 12               3,0   

   relationshipsatisfaction standardhours  stockoptionlevel totalworkingyears  \
0                         3     Full Time                 0               NaN   
1                         1           NaN                 1              34,0   
2                         4           NaN                 0              22,0   
3                         2     Full Time                 2               NaN   
4                         4           NaN                 1               NaN   

   trainingtimeslastyear worklifebalance  yearsatcompany yearsincurrentrole  \
0                      5             3,0              20                NaN   
1                      5             3,0              33                NaN   
2                      3             NaN              22                NaN   
3                      2             NaN              20                NaN   
4                      5             3,0              19                NaN   

   yearssincelastpromotion  yearswithcurrmanager  datebirth      salary  \
0                       15                    15       1972  195370,00$   
1                       11                     9       1971  199990,00$   
2                       11                    15       1981  192320,00$   
3                        5                     6       1976  171690,00$   
4                        2                     8       1977         NaN   

                      roledepartament remotework  
0                                 NaN        Yes  
1                                 NaN          1  
2  manager  -  research & development          1  
3                                 NaN      False  
4                                 NaN          0

In [360]:
df["age"].unique()

array([52, 53, 43, 48, 47, 49, 60, 42, 57, 39, 56, 41, 59, 36, 46, 34, 37,
       35, 54, 44, 61, 33, 38, 50, 40, 51, 45, 31, 30, 32, 55, 58, 28, 29,
       27, 26, 25, 24, 23, 22, 21, 20, 19], dtype=int64)

In [361]:
df["age"].dtype

dtype('int64')

In [362]:
# TAREA 3 Cambio tipo de columnas de object a float: monthlyincome($), monthlyrate($), salary($) , worklifebalance performancerating, yearsincurrentrole


In [363]:
# Son los 4 tipo object y pasaran a float 
df["monthlyincome"].unique() # Tiene $, nulos, ni puntos
df["monthlyrate"].unique() # Tiene $, NO TIENE nulos, ni puntos
df["salary"].unique() # Tiene $, nulos, ni puntos
df["performancerating"].unique()  # NO Tiene $, nulos -> 

array(['3,0', '4,0', nan], dtype=object)

In [ ]:
def cambiar_tipo_dato(col):
    """
    Convierte los valores de una columna de tipo objeto a tipo float.

    - Elimina el símbolo `$` y reemplaza las comas `,` por puntos `.` en los valores.
    - Convierte los valores resultantes a tipo `float`.
    - Si el valor es `NaN`, lo conserva como `np.nan`.

    Parámetros:
        col (str): El valor de la columna a procesar (de tipo cadena u objeto).

    Retorna:
        float: El valor convertido a tipo flotante, o `np.nan` si el valor original era nulo.

    Notas:
        Si ocurre un error durante la conversión, imprime un mensaje indicando el error.
    """
    try: 
        print('Entro en try')
        if pd.isna(col):  # Verificar si el valor es NaN
            return np.nan
        else:  # Es necesario pq sino devuelve todo nulos (sólo en los valores tipo float, no sé pq)
            col = col.replace(",", ".").replace('$', '')  # Reemplazar la coma por punto y eliminar '$' 
            print(f'Primer replace: {col}')
            return float(col)
    except:
        print('Ha ocurrido un error')

In [365]:
df[["monthlyincome", "monthlyrate", "salary", "performancerating", "worklifebalance", "yearsincurrentrole"]].info()

<class 'pandas.core.frame.DataFrame'>
Index: 1614 entries, 0 to 1613
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   monthlyincome       1146 non-null   object
 1   monthlyrate         1614 non-null   object
 2   salary              1340 non-null   object
 3   performancerating   1419 non-null   object
 4   worklifebalance     1506 non-null   object
 5   yearsincurrentrole  34 non-null     object
dtypes: object(6)
memory usage: 88.3+ KB


In [ ]:
lista_columnas = ["monthlyincome", "monthlyrate", "salary", "performancerating", "worklifebalance", "yearsincurrentrole"]
for columna in lista_columnas:
    df[columna] = df[columna].apply(cambiar_tipo_dato)

In [367]:
df[["monthlyincome", "monthlyrate", "salary", "performancerating", "worklifebalance", "yearsincurrentrole"]].info()

<class 'pandas.core.frame.DataFrame'>
Index: 1614 entries, 0 to 1613
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   monthlyincome       1146 non-null   float64
 1   monthlyrate         1614 non-null   float64
 2   salary              1340 non-null   float64
 3   performancerating   1419 non-null   float64
 4   worklifebalance     1506 non-null   float64
 5   yearsincurrentrole  34 non-null     float64
dtypes: float64(6)
memory usage: 88.3 KB


In [368]:
df_salary = df[['monthlyincome', 'salary']]

df_salary

monthlyincome     salary
0          16280.83  195370.00
1               NaN  199990.00
2               NaN  192320.00
3          14307.50  171690.00
4          12783.92        NaN
...             ...        ...
1609        8604.17  103250.00
1610        3705.83   44470.00
1611            NaN  100071.84
1612        4492.84   53914.11
1613        9037.50  108450.00

[1614 rows x 2 columns]

In [369]:
def actualizar_nulos(df):
    # Reemplazar valores nulos en 'monthlyincome' con el valor de 'salary' / 12
    df['monthlyincome'] = df.apply(
        lambda row: np.round((row['salary'] / 12), 2) if pd.isna(row['monthlyincome']) else row['monthlyincome'], axis=1
    )
    
    # Reemplazar valores nulos en 'salary' con el valor de 'monthlyincome' * 12
    df['salary'] = df.apply(
        lambda row: np.round((row['monthlyincome'] * 12), 2) if pd.isna(row['salary']) else row['salary'], axis=1
    )
    
    return df

In [ ]:
actualizar_nulos(df_salary)

In [177]:
df_salary = df[['monthlyincome', 'salary']]

In [375]:
df_salary.isna().sum()

monthlyincome    0
salary           0
dtype: int64

# GRUPO 2

In [66]:
#corrección de 'maritalstatus' df['gender'] = df['gender'].replace(1, 'F').replace(0, 'M')

df['maritalstatus'] = df['maritalstatus'].replace('Marreid','Married').str.lower()
df['maritalstatus'].unique()

array([nan, 'married', 'divorced', 'single'], dtype=object)

In [67]:
#corregir valores negativos en 'distancefromhome'
df['distancefromhome'] = df['distancefromhome'].apply(lambda x: -x if x < 0 else x)
df['distancefromhome'].unique()

array([ 6,  1,  4,  2,  3, 22, 25,  9,  7, 23, 10, 12, 14, 13, 15,  8, 42,
       28, 37,  5, 16, 35, 26, 24, 29, 17, 21, 18, 30, 27, 20, 31, 39, 11,
       19, 33, 34, 46, 36, 45, 47, 32, 41, 49, 48, 38, 43, 40, 44])

In [68]:
#unificar 'remotework'
dicc_remote = {'0':'no','1':'si','True':'si','False':'no'}
df['remotework'] = df['remotework'].map(dicc_remote)
df['remotework'].unique()

array([nan, 'si', 'no'], dtype=object)

In [69]:
#businesstravel -> poner los nan como non travel
df['businesstravel'] = df['businesstravel'].fillna('non-travel')
df['businesstravel'].unique()

array(['non-travel', 'travel_rarely', 'travel_frequently'], dtype=object)

In [70]:
#correción 'environmentsatisfaction'
df['environmentsatisfaction'] = df['environmentsatisfaction'].astype(str).str.extract(r'^([1-4])', expand=False).fillna(df['environmentsatisfaction']).astype(int)
df['environmentsatisfaction'].unique()

array([1, 3, 4, 2])